clear; clc; close all;

filePath = 'C:\Users\usr\hyperloop_test_data.csv';
if ~exist(filePath, 'file')
    error('Dont exist');
end

opts = detectImportOptions(filePath);
opts.VariableNamingRule = 'preserve';
data = readtable(filePath, opts);

try
    t_raw = datetime(data.Timestamp, 'InputFormat', 'HH:mm:ss');
    t_sec = seconds(t_raw - t_raw(1)); 
catch
    t_sec = (0:height(data)-1)' * 0.05; 
end

fig = figure('Name', 'Telemetry Analysis', ...
    'Color', 'k', 'Units', 'normalized', 'Position', [0.1 0.1 0.7 0.8]);

sgtitle('Dynamic Breaking Characteristics', ...
    'FontWeight','bold', 'FontSize',15, ...
    'Interpreter','none', 'Color','w', 'FontName','Helvetica');

%% -------------------- SUBPLOT 1 --------------------
subplot(3,1,1);
plot(t_sec, data.Mesafe_cm, 'LineWidth', 2, 'Color', '#0072BD');
ylabel('Distance [cm]', ...
    'FontWeight','bold', 'FontSize',12, ...
    'Interpreter','none', 'Color','w', 'FontName','Helvetica');
grid on; grid minor;
set(gca, ...
    'FontSize',11, ...
    'TickLabelInterpreter','latex', ...
    'XColor','w', 'YColor','w', ...
    'Color','k');
legend('Lidar/Ultrasonic Feedback', ...
    'FontWeight','bold', 'FontSize',11, ...
    'Interpreter','none', 'TextColor','w', ...
    'Location','northeast', 'FontName','Helvetica');

%% -------------------- SUBPLOT 2 --------------------
subplot(3,1,2);
stairs(t_sec, data.Aci_Derece, 'LineWidth', 2, 'Color', '#D95319');
ylabel('Angle [deg]', ...
    'FontWeight','bold', 'FontSize',12, ...
    'Interpreter','none', 'Color','w', 'FontName','Helvetica');
grid on; grid minor;
set(gca, ...
    'FontSize',11, ...
    'TickLabelInterpreter','latex', ...
    'XColor','w', 'YColor','w', ...
    'Color','k');
legend('Servo Output (\theta)', ...
    'FontWeight','bold', 'FontSize',11, ...
    'Interpreter','none', 'TextColor','w', ...
    'Location','northeast', 'FontName','Helvetica');

%% -------------------- SUBPLOT 3 --------------------
subplot(3,1,3);
plot(t_sec, data.Akim_A, 'LineWidth', 1.5, 'Color', '#77AC30');
xlabel('Time [s]', ...
    'FontWeight','bold', 'FontSize',12, ...
    'Interpreter','none', 'Color','w', 'FontName','Helvetica');
ylabel('Current [mA]', ...
    'FontWeight','bold', 'FontSize',12, ...
    'Interpreter','none', 'Color','w', 'FontName','Helvetica');
grid on; grid minor;
set(gca, ...
    'FontSize',11, ...
    'TickLabelInterpreter','latex', ...
    'XColor','w', 'YColor','w', ...
    'Color','k');
legend('ACS712 Sensor Data', ...
    'FontWeight','bold', 'FontSize',11, ...
    'Interpreter','none', 'TextColor','w', ...
    'Location','northeast', 'FontName','Helvetica');

%% -------------------- AXIS LINK --------------------
linkaxes(findall(gcf,'type','axes'), 'x');
xlim([0 max(t_sec)]);

fprintf(': %s\n', filePath);
